k9s:
  cluster: minikube
  namespace:
    active: autogen-test
    lockFavorites: false
    favorites:
      - autogen-test
      - verify-dlp-on-passthrough
      - speedscale-test
      - echo
      - smart-replace-demo
      - microservices
      - speedscale
      - grpc
      - default
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
