#!/usr/bin/env bash

set -eou pipefail

function op_exit() {
  if [ "$?" -ne 0 ]; then
    echo "======================"
		echo "=== !!! FAILED !!! ==="
    echo "======================"
  fi
}
trap op_exit EXIT

# ensure we are in the right dir
cd "$(dirname "$0")"

{
  echo "======================"
  echo "=== pulling master ==="
	echo "======================"

  pushd master > /dev/null

  git pull
  worktrees=$(git worktree list | awk '{print $1}' | grep -v 'master' || true)

  popd > /dev/null
}

function rebase() {
  echo
  echo "====================="
  echo "=== rebasing ${1} ==="
  echo "====================="

  pushd "$1" > /dev/null

  stash=false
  if [ -n "$(git status -s && git status | rg "git push")" ]; then
    stash=true
  fi

  if $stash; then
    git stash -um "hold for rebase"
  fi

  git rebase origin/master

  if $stash; then
    git stash pop
  fi

  popd > /dev/null
}

echo
for d in $worktrees; do
	rebase "$d"
done

echo
echo "==============="
echo "=== SUCCESS ==="
echo "==============="

