#!/usr/bin/env bash

set -eo pipefail

function list_remote() {
  line="=== remotes for $1 ==="
  length=${#line}
  separator=$(printf '%0.s=' $(seq 1 "$length"))

  echo "$separator"
  echo "=== remotes for ${1} ==="
  echo "$separator"

  pushd "$1" > /dev/null

  glab mr list --source-branch "$(git rev-parse --abbrev-ref HEAD)" | cut -d '!' -f '3' || true
  glab mr list --source-branch "$(git rev-parse --abbrev-ref HEAD)" -M | cut -d '!' -f '3' || true

  popd > /dev/null
}

if [ -n "$1" ]; then
	list_remote "$1"
  exit
fi

worktrees=$(cd master && git worktree list | awk '{print $1}' | grep -v 'master') || true
for d in $worktrees; do
	list_remote "$d"
done

