k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 300
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: minikube
  currentCluster: minikube
  clusters:
    arn:aws:eks:us-east-1:094668123143:cluster/dev-sstenant-eks-cluster:
      namespace:
        active: sstenant-external
        lockFavorites: false
        favorites:
        - all
        - sstenant-trials
        - sstenant-guest
        - sstenant-experimental
        - sstenant-external
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-1:853014245683:cluster/staging-sstenant-eks-cluster:
      namespace:
        active: sstenant-elastic
        lockFavorites: false
        favorites:
        - sstenant-elastic
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-1:880246755038:cluster/prod-sstenant-eks-cluster:
      namespace:
        active: sstenant-000202
        lockFavorites: false
        favorites:
        - sstenant-000377
        - sstenant-000834
        - sstenant-speedscale
        - sstenant-cfacorp
        - sstenant-000689
        - default
      view:
        active: ns
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_speedscale-demos_us-central1_dev-decoy:
      namespace:
        active: beta-services
        lockFavorites: false
        favorites:
        - speedscale
        - beta-services
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_speedscale-demos_us-central1_kraken:
      namespace:
        active: speedscale
        lockFavorites: false
        favorites:
        - speedscale
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_speedscale-demos_us-central1_prod-decoy:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    minikube:
      namespace:
        active: speedscale
        lockFavorites: false
        favorites:
        - beta-services
        - speedscale
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/hy/sxcwypzn0h9bg08bpjz789y00000gn/T/k9s-screens-josh
