plugin:
  #################
  ### DEBUGGING ###
  #################
  dive: # view container details with dive
  netshoot:
    shortCut: Shift-D
    description: "Add debug container (netshoot)"
    scopes:
      - containers
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "kubectl debug -it -n=$NAMESPACE $POD --target=$NAME --image=nicolaka/netshoot:v0.11 --share-processes -- bash"
    shortCut: d
    confirm: true
    description: "Dive image"
    scopes:
      - containers
    command: dive
    background: false
    args:
      - $COL-IMAGE
  log-more:
    shortCut: m
    description: "Log more"
    scopes:
      - containers
    command: bash
    background: true
    confirm: false
    args:
      - -c
      - "kubectl --context $CONTEXT -n=$NAMESPACE exec $POD -- bash -c 'kill -s sigusr1 1'"
  log-less:
    shortCut: Shift-L
    description: "Log less"
    scopes:
      - containers
    command: bash
    background: true
    confirm: false
    args:
      - -c
      - "kubectl --context $CONTEXT -n=$NAMESPACE exec $POD -- bash -c 'kill -s sigusr2 1'"
  connect-db:
    shortCut: Ctrl-L
    description: "Connect to DB"
    scopes:
      - pods
    command: zsh
    background: false
    confirm: true
    args:
      - -c
      - "source ~/.zshrc-db && CONTEXT=$CONTEXT NAMESPACE=$NAMESPACE connect-db $NAME || sleep 5"
  pv-usage:
    shortCut: Shift-U
    description: "Show usage"
    scopes:
      - persistentvolumes
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "kubectl df-pv --context $CONTEXT | less"


  ############
  ### FLUX ###
  ############
  toggle-helmrelease:
    shortCut: Shift-T
    confirm: true
    scopes:
      - helmreleases
    description: Toggle to suspend or resume a HelmRelease
    command: bash
    background: false
    args:
      - -c
      - "flux --context $CONTEXT $([ $(kubectl --context $CONTEXT get helmreleases -n $NAMESPACE $NAME -o=custom-columns=TYPE:.spec.suspend | tail -1) = \"true\" ] && echo \"resume\" || echo \"suspend\") helmrelease -n $NAMESPACE $NAME |& less"
  toggle-kustomization:
    shortCut: Shift-T
    confirm: true
    scopes:
      - kustomizations
    description: Toggle to suspend or resume a Kustomization
    command: bash
    background: false
    args:
      - -c
      - "flux --context $CONTEXT $([ $(kubectl --context $CONTEXT get kustomizations -n $NAMESPACE $NAME -o=custom-columns=TYPE:.spec.suspend | tail -1) = \"true\" ] && echo \"resume\" || echo \"suspend\") kustomization -n $NAMESPACE $NAME |& less"
  reconcile-git:
    shortCut: Shift-R
    confirm: true
    description: Flux reconcile
    scopes:
      - gitrepositories
    command: bash
    background: false
    args:
      - -c
      - "flux --context $CONTEXT reconcile source git -n $NAMESPACE $NAME |& less"
  reconcile-hr:
    shortCut: Shift-R
    confirm: true
    description: Flux reconcile
    scopes:
      - helmreleases
    command: bash
    background: false
    args:
    - -c
    - "flux --context $CONTEXT reconcile helmrelease -n $NAMESPACE $NAME |& less"
  reconcile-helm-repo:
    shortCut: Shift-Z
    description: Flux reconcile
    scopes:
      - helmrepositories
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "flux reconcile source helm --context $CONTEXT -n $NAMESPACE $NAME |& less"
  reconcile-oci-repo:
    shortCut: Shift-Z
    description: Flux reconcile
    scopes:
      - ocirepositories
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "flux reconcile source oci --context $CONTEXT -n $NAMESPACE $NAME |& less"
  reconcile-ks:
    shortCut: Shift-R
    confirm: true
    description: Flux reconcile
    scopes:
      - kustomizations
    command: bash
    background: false
    args:
      - -c
      - "flux --context $CONTEXT reconcile kustomization -n $NAMESPACE $NAME |& less"
  trace:
    shortCut: Shift-A
    confirm: true
    description: Flux trace
    scopes:
      - helmrepositories
      - gitrepositories
      - kustomizations
      - helmreleases
      - ocirepositories
    command: bash
    background: false
    args:
      - -c
      - "flux --context $CONTEXT trace --kind `echo $RESOURCE_NAME | sed -E 's/ies$/y/' | sed -E 's/ses$/se/' | sed -E 's/(s|es)$//g'` --api-version $RESOURCE_GROUP/$RESOURCE_VERSION --namespace $NAMESPACE $NAME |& less"
